---
- name: Set facts for HPE iLO4 Redfish endpoints
  ansible.builtin.set_fact:
    redfish_manager_endpoint: "https://{{ host.endpoint }}/redfish/v1/Managers/1/"
    redfish_system_endpoint: "https://{{ host.endpoint }}/redfish/v1/Systems/1/"
    redfish_virtual_media_endpoint: "https://{{ host.endpoint }}/redfish/v1/Managers/1/VirtualMedia/2/" # 1 is for a floppy, 2 is for a CD
    redfish_virtual_media_insert_endpoint: "https://{{ host.endpoint }}/redfish/v1/Managers/1/VirtualMedia/2/Actions/Oem/Hp/HpiLOVirtualMedia.InsertVirtualMedia/"
    redfish_virtual_media_eject_endpoint: "https://{{ host.endpoint }}/redfish/v1/Managers/1/VirtualMedia/2/Actions/Oem/Hp/HpiLOVirtualMedia.EjectVirtualMedia/"
    redfish_reboot_endpoint: "https://{{ host.endpoint }}/redfish/v1/Systems/1/Actions/ComputerSystem.Reset/"