---

- name: Insert Virtual Media
  community.general.redfish_command:
    category: Systems
    command: VirtualMediaInsert
    baseuri: "{{ host.endpoint }}"
    username: "{{ host.username }}"
    password: "{{ host.password }}"
    virtual_media:
      image_url: "http://{{ http_server_ip }}:{{ http_server_port | default('7654') }}/{{ iso_name | default('agent_x86_64.iso') }}"
      media_types:
        - CD
        - DVD
    resource_id: 1
  register: virtual_media_result

- name: Print fetched information
  ansible.builtin.debug:
    msg: "{{ virtual_media_result }}"
