---
- name: Force Reset the system - SuperMicro
  ansible.builtin.uri:
    force_basic_auth: true
    user: "{{ host.username }}"
    password: "{{ host.password }}"
    validate_certs: false
    return_content: true
    method: POST
    url: "{{ redfish_reboot_endpoint }}"
    body_format: json
    body: '{"ResetType": "ForceRestart"}'
  register: redfish_reset_result

- name: Debug the result of the reset - SuperMicro
  when: debug_redfish
  ansible.builtin.debug:
    msg: "{{ redfish_reset_result }}"
