# Make sure to run `ansible-galaxy collection install infra.controller_configuration` before this playbook
---
- name: Configure an Ansible Automation Platform Controller to use the included content
  hosts: localhost
  connection: local

  vars:
  # Define following vars here, or in controller_configs/controller_auth.yml
  # controller_hostname: ansible-controller-web-svc-test-project.example.com
  # controller_username: admin
  # controller_password: changeme

  pre_tasks:
    - name: Include vars from controller_configs directory
      ansible.builtin.include_vars:
        dir: ./vars
        ignore_files: [controller_config.yml.template]
        extensions: ["yml"]

  roles:
    - {role: infra.controller_configuration.execution_environments, when: controller_execution_environments is defined}
    - {role: infra.controller_configuration.projects, when: controller_projects is defined}
    - {role: infra.controller_configuration.inventories, when: controller_inventories is defined}
    - {role: infra.controller_configuration.hosts, when: controller_hosts is defined}
    - {role: infra.controller_configuration.job_templates, when: controller_templates is defined}