---
- name: Insert the target ISO into the Virtual CD Device - sushy-tools
  ansible.builtin.uri:
    #force_basic_auth: true
    #user: "{{ host.username }}"
    #password: "{{ host.password }}"
    validate_certs: false
    return_content: true
    method: POST
    url: "{{ redfish_virtual_media_insert_endpoint }}"
    body_format: json
    body: '{"Image": "{{ iso_url }}", "Inserted": true}'
    status_code: 204
    timeout: 300
  register: redfish_virtual_media_insert_result

- name: Debug the result of the virtual media insert - sushy-tools
  when: debug_redfish
  ansible.builtin.debug:
    msg: "{{ redfish_virtual_media_insert_result }}"
