---
- name: Get system information from a BMC via Redfish
  hosts: localhost
  gather_facts: true
  vars:
    iso_url_host: http://deep-thought.kemo.labs:9080
    iso_url_path: /linux/isos/rhel-9.2-x86_64-dvd.iso

    # OR

    http_server_ip: 192.168.42.40
    http_server_path: /tmp/ocp-http-boot
    iso_name: agent.x86_64.iso
    iso_path: /opt/workdir/openshift-agent-install/openshift-agent-install/generated_manifests/suki-sno/agent.x86_64.iso

    bmc_hosts:
      - name: endurance
        endpoint: endurance.mgmt.kemo.labs
        username: ansible
        password: n0tPassword
        system_type: supermicro

      - name: serenity
        endpoint: serenity.mgmt.kemo.labs
        username: root
        password: lolpenis
        system_type: iDRAC8

  tasks:

    - name: Host entry point task
      ansible.builtin.include_tasks:
        file: tasks/host_entrypoint.yml
      loop: "{{ bmc_hosts }}"
      loop_control:
        loop_var: host
      

    #- name: Get system info
    #  ansible.builtin.include_tasks:
    #    file: tasks/get_redfish_system_info.yml
    #  loop: "{{ bmc_hosts }}"
    #  loop_control:
    #    loop_var: host

    - name: Start a web server and copy over the target ISO
      when: iso_url is not defined
      block:

        - name: Start the HTTP server
          ansible.builtin.include_tasks:
            file: tasks/start_http_server.yml

        - name: Copy the ISO to the target path
          ansible.builtin.copy:
            src: "{{ iso_path }}"
            dest: "{{ http_server_path }}/{{ iso_name }}"
            remote_src: true
            mode: 0755

    #- name: Set the Redfish virtual media device
    #  ansible.builtin.include_tasks:
    #    file: tasks/set_virtual_media.yml
    #  loop: "{{ bmc_hosts }}"
    #  loop_control:
    #    loop_var: host