---
- name: Boot systems from an ISO via Redfish
  hosts: localhost
  gather_facts: false
  vars:
    debug_redfish: false

    iso_url: http://deep-thought.kemo.labs:9080/linux/isos/rhel-9.2-x86_64-dvd.iso

    bmc_hosts:
      - name: endurance
        endpoint: endurance.mgmt.kemo.labs
        username: ansible
        password: n0tPassword
        system_type: supermicro

      - name: serenity
        endpoint: serenity.mgmt.kemo.labs
        username: ansible
        password: n0tPassword
        system_type: iDRAC8

  tasks:

    - name: Host entry point task
      ansible.builtin.include_tasks:
        file: tasks/host_entrypoint.yml
      loop: "{{ bmc_hosts }}"
      loop_control:
        loop_var: host
